# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate proc-macro-hack-impl

Name:           rust-proc-macro-hack-impl
Version:        0.4.3
Release:        %autorelease
Summary:        Procedural functionlike!() macros using only Macros 1.1

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/proc-macro-hack-impl
Source0         %{crates_source}

# Use license files from the upstream project
# commit is the tag for 0.4.3
Source1:        https://raw.githubusercontent.com/dtolnay/proc-macro-hack/ed464c1a24528cbf270fd9f14cf22e851daa6870/LICENSE-APACHE
Source2:        https://github.com/dtolnay/proc-macro-hack/blob/ed464c1a24528cbf270fd9f14cf22e851daa6870/LICENSE-MIT

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Procedural functionlike!() macros using only Macros 1.1.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE-APACHE
%license LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
cp "%{SOURCE1}" .
cp "%{SOURCE2}" .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
