# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate smallvec

Name:           rust-smallvec0.6
Version:        0.6.14
Release:        2
Summary:        'Small vector' optimization: store up to a small number of items on the stack

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/smallvec
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
'Small vector' optimization: store up to a small number of items on the stack.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE-APACHE
%license LICENSE-MIT
%doc README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+may_dangle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+may_dangle-devel %{_description}

This package contains library source intended for building other packages which
use the "may_dangle" feature of the "%{crate}" crate.

%files       -n %{name}+may_dangle-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+specialization-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+specialization-devel %{_description}

This package contains library source intended for building other packages which
use the "specialization" feature of the "%{crate}" crate.

%files       -n %{name}+specialization-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+union-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+union-devel %{_description}

This package contains library source intended for building other packages which
use the "union" feature of the "%{crate}" crate.

%files       -n %{name}+union-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Jan 24 2023 David Shea <reallylongword@gmail.com> - 0.6.14-2
- Remove rpmautospec macros

* Sun Oct 16 2022 David Shea <reallylongword@gmail.com> - 0.6.14-1
- Initial package
