# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate criterion

Name:           rust-criterion0.2
Version:        0.2.11
Release:        %autorelease
Summary:        Statistics-driven micro-benchmarking library

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/criterion
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Statistics-driven micro-benchmarking library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE-APACHE
%license LICENSE-MIT
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+criterion-plot-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+criterion-plot-devel %{_description}

This package contains library source intended for building other packages which
use the "criterion-plot" feature of the "%{crate}" crate.

%files       -n %{name}+criterion-plot-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+html_reports-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+html_reports-devel %{_description}

This package contains library source intended for building other packages which
use the "html_reports" feature of the "%{crate}" crate.

%files       -n %{name}+html_reports-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real_blackbox-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real_blackbox-devel %{_description}

This package contains library source intended for building other packages which
use the "real_blackbox" feature of the "%{crate}" crate.

%files       -n %{name}+real_blackbox-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tinytemplate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tinytemplate-devel %{_description}

This package contains library source intended for building other packages which
use the "tinytemplate" feature of the "%{crate}" crate.

%files       -n %{name}+tinytemplate-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
