# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate rpm-rs

Name:           rust-rpm-rs
Version:        0.8.1
Release:        %autorelease
Summary:        Pure rust library for building and parsing RPM's

License:        Apache-2.0
URL:            https://crates.io/crates/rpm-rs
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Pure rust library for building and parsing RPM's.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "async-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+async-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pgp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pgp-devel %{_description}

This package contains library source intended for building other packages which
use the "pgp" feature of the "%{crate}" crate.

%files       -n %{name}+pgp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+signature-meta-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+signature-meta-devel %{_description}

This package contains library source intended for building other packages which
use the "signature-meta" feature of the "%{crate}" crate.

%files       -n %{name}+signature-meta-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+signature-pgp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+signature-pgp-devel %{_description}

This package contains library source intended for building other packages which
use the "signature-pgp" feature of the "%{crate}" crate.

%files       -n %{name}+signature-pgp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-with-podman-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-with-podman-devel %{_description}

This package contains library source intended for building other packages which
use the "test-with-podman" feature of the "%{crate}" crate.

%files       -n %{name}+test-with-podman-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
