# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate ed25519-dalek

Name:           rust-ed25519-dalek
Version:        1.0.1
Release:        %autorelease
Summary:        Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust

License:        BSD-3-Clause
URL:            https://crates.io/crates/ed25519-dalek
Source:         %{crates_source}

# TESTVECTORS is not distributed with the crate and is required for the `against_reference_implementation` test
# The git commit is the commit for the 1.0.1 tag on github. The file never changes though so the exact commit isn't
# really important.
Source1:        https://raw.githubusercontent.com/dalek-cryptography/ed25519-dalek/1042cb60a07cdaacb59ca209716b69f444460f8f/TESTVECTORS

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Fast and efficient ed25519 EdDSA key generations, signing, and verification in
pure Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+asm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+asm-devel %{_description}

This package contains library source intended for building other packages which
use the "asm" feature of the "%{crate}" crate.

%files       -n %{name}+asm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+batch-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+batch-devel %{_description}

This package contains library source intended for building other packages which
use the "batch" feature of the "%{crate}" crate.

%files       -n %{name}+batch-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+batch_deterministic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+batch_deterministic-devel %{_description}

This package contains library source intended for building other packages which
use the "batch_deterministic" feature of the "%{crate}" crate.

%files       -n %{name}+batch_deterministic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+legacy_compatibility-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+legacy_compatibility-devel %{_description}

This package contains library source intended for building other packages which
use the "legacy_compatibility" feature of the "%{crate}" crate.

%files       -n %{name}+legacy_compatibility-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+merlin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+merlin-devel %{_description}

This package contains library source intended for building other packages which
use the "merlin" feature of the "%{crate}" crate.

%files       -n %{name}+merlin-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages which
use the "rand" feature of the "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand_core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand_core-devel %{_description}

This package contains library source intended for building other packages which
use the "rand_core" feature of the "%{crate}" crate.

%files       -n %{name}+rand_core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_bytes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_bytes-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_bytes" feature of the "%{crate}" crate.

%files       -n %{name}+serde_bytes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_crate-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_crate" feature of the "%{crate}" crate.

%files       -n %{name}+serde_crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd_backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd_backend-devel %{_description}

This package contains library source intended for building other packages which
use the "simd_backend" feature of the "%{crate}" crate.

%files       -n %{name}+simd_backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u32_backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u32_backend-devel %{_description}

This package contains library source intended for building other packages which
use the "u32_backend" feature of the "%{crate}" crate.

%files       -n %{name}+u32_backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u64_backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u64_backend-devel %{_description}

This package contains library source intended for building other packages which
use the "u64_backend" feature of the "%{crate}" crate.

%files       -n %{name}+u64_backend-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
cp %{SOURCE1} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
